"""Domain Knowledge Spec Drafter — UC-11.

Reads knowledge source files and produces a draft wiki spec defining ingestion
needs, governance, quality metrics, and domain partitioning.
Does not require the semantic layer to exist.
"""

import logging
import re
import time
import uuid
from datetime import UTC, datetime
from pathlib import Path

from claude_code_sdk import ClaudeCodeOptions, ResultMessage, query

from ea_workbench.agents.base import write_manifest
from ea_workbench.models.config import AgentConfig
from ea_workbench.models.manifests import RunManifest

logger = logging.getLogger(__name__)

AGENT_ID = "domain-knowledge-spec"

_DEFAULT_TEMPLATE = """---
parent: index
title: {Domain Name} — Domain Knowledge Spec
domain: unknown
status: draft
version: "0.1"
---

# Domain Knowledge Spec

## Purpose

## Domain Boundaries

## Knowledge Sources

## Key Concepts

## Data Entities

## Ingestion Needs

## Governance Model

## Quality Metrics

## Domain Partitioning

## Open Questions

---
*Draft generated by EA Workbench domain-knowledge-spec agent. Human review required.*
"""


def _load_spec_template(workspace: str) -> str:
    """Read the domain knowledge spec template or return embedded default.

    Args:
        workspace: Path to the PFC workspace root.

    Returns:
        Template content string.
    """
    template_path = (
        Path(workspace) / "specs" / "_templates" / "domain-knowledge-spec.md"
    )
    if template_path.exists():
        try:
            return template_path.read_text(encoding="utf-8")
        except Exception as exc:
            logger.warning("Could not read spec template: %s", exc)
    return _DEFAULT_TEMPLATE


def _slug_from_path(path: str) -> str:
    """Normalise a file path to a URL-safe slug.

    Args:
        path: File path string.

    Returns:
        Lowercase hyphenated slug.
    """
    name = Path(path).stem
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "domain"


async def run(config: AgentConfig, prompt: str, workspace: str) -> RunManifest:
    """Execute the domain knowledge spec drafter.

    `prompt` is treated as the knowledge source file path.

    Args:
        config: Agent configuration from config.yaml.
        prompt: File path of the knowledge source to analyse.
        workspace: Path to the PFC workspace root.

    Returns:
        Completed RunManifest. Draft spec written to output/specs/.
    """
    run_id = str(uuid.uuid4())[:8]
    timestamp = datetime.now(UTC).isoformat().replace("+00:00", "Z")
    start = time.monotonic()
    runs_dir = str(Path(workspace) / ".agents" / "runs")

    # Resolve source file path
    source_path = (
        Path(prompt) if Path(prompt).is_absolute() else Path(workspace) / prompt
    )
    slug = _slug_from_path(str(source_path))

    # Load template
    template = _load_spec_template(workspace)

    # Load system prompt
    prompt_path = Path(workspace) / config.prompt
    try:
        system_prompt = prompt_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        system_prompt = (
            "You are a domain knowledge spec drafter. "
            "Read the source files and produce a draft wiki spec."
        )

    model = config.model if "${" not in config.model else "claude-sonnet-4-6"

    template_used = "custom" if "custom" not in template.lower() else "default"
    template_used = (
        "custom"
        if (Path(workspace) / "specs" / "_templates" / "domain-knowledge-spec.md").exists()
        else "default"
    )

    agent_prompt = (
        f"Draft a domain knowledge spec for the knowledge source at '{source_path}'. "
        f"Use the following template structure:\n\n{template}\n\n"
        f"Write the draft spec to 'output/specs/dk-{slug}.md' in workspace '{workspace}'."
    )

    result_text = ""
    run_status = "completed"
    error_msg: str | None = None
    tokens_consumed = 0

    try:
        options = ClaudeCodeOptions(
            system_prompt=system_prompt,
            allowed_tools=config.tools or ["Read", "Write"],
            cwd=workspace,
            model=model,
            max_turns=8,
            permission_mode="acceptEdits",
        )
        async for message in query(prompt=agent_prompt, options=options):
            if isinstance(message, ResultMessage):
                result_text = message.result or ""
                if message.usage:
                    tokens_consumed = (
                        message.usage.get("input_tokens", 0)
                        + message.usage.get("output_tokens", 0)
                    )
                if message.is_error:
                    run_status = "failed"
                    error_msg = result_text
    except Exception as exc:
        logger.error("Domain knowledge spec SDK error: %s", exc)
        run_status = "failed"
        error_msg = str(exc)
        result_text = f"# Domain Knowledge Spec\n\n⚠️ Agent error: {exc}"

    # Write output
    output_dir = Path(workspace) / "output" / "specs"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"dk-{slug}.md"

    if not result_text:
        result_text = f"# Domain Knowledge Spec — {slug}\n\nNo draft produced."

    # Check if agent wrote it already; if not, write result_text
    if not output_file.exists():
        output_file.write_text(result_text, encoding="utf-8")

    duration = time.monotonic() - start
    manifest = RunManifest(
        agent_id=AGENT_ID,
        run_id=run_id,
        triggered_by="manual",
        timestamp=timestamp,
        duration_seconds=duration,
        model_used=model,
        tokens_consumed=tokens_consumed,
        status=run_status,
        inputs=[str(source_path)],
        outputs=[str(output_file)],
        summary={
            "template_used": template_used,
            "output_spec": str(output_file),
        },
        error=error_msg,
    )

    write_manifest(manifest, runs_dir)
    return manifest
